name: Release Charts

on:
  push:
    branches:
      # - main
      - github-actions-deploy
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up SSH agent with private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Copy files to remote server
      #   run: |
      #     rsync --archive --verbose --compress --delete \
      #       --rsh='ssh -o StrictHostKeyChecking=no' \
      #       --exclude='.git*' \
      #       --exclude='.github/' \
      #       ./ \
      #       ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_ALAVETELI_INSTALL_PATH }}/lib/themes/handlingar-theme

      - name: Set theme target branch
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          ssh -o StrictHostKeyChecking=no \
            ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} \
            "sed -i \"s/^THEME_BRANCH: '.*'/THEME_BRANCH: '${CURRENT_BRANCH//'/'_}'/\" \
            ${{ vars.SSH_ALAVETELI_INSTALL_PATH }}/config/general.yml"
      - name: Install theme
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "cd ${{ vars.SSH_ALAVETELI_INSTALL_PATH }} && bundle exec rake themes:install RAILS_ENV=production"
